# Generated by Django 3.2 on 2021-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vaccination_date',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
