# Generated by Django 3.2 on 2021-05-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_vaccination_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='vaccination_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vaccination_place',
        ),
    ]
